import "./globals.css";

import localFont from "next/font/local";

const customFont = localFont({
  src: [
    {
      path: "./fonts/ExpoArabic-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/ExpoArabic-Light.ttf",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-custom",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${customFont.className} antialiased m-0 p-0`}>
        {children}
      </body>
    </html>
  );
}
