import type { Metadata } from "next";
import "./globals.css";
import TranslationsProvider from "@/localization/TranslationsProvider";
import initTranslations from "@/localization/i18n";
import localFont from "next/font/local";
import ReactQueryProvider from "@/providers/ReactQueryProvider";

const sfProArabic = localFont({
  src: "../fonts/EXPO-ARABIC-BOOK.TTF",
  variable: "--font-arabic",
  display: "swap",
});

const sfPro = localFont({
  src: "../fonts/EXPO-ARABIC-BOOK.TTF",
  variable: "--font-english",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Isnad",
  description: "Generated by create next app",
};

const i18bNamespaces = [
  "home_transtion"
];

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const { resources } = await initTranslations(locale, i18bNamespaces);
  const fontClassName =
    locale === "ar" ? sfProArabic.className : sfPro.className;

  return (
    <html
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      data-theme="default"
      className={fontClassName}
      suppressHydrationWarning
    >
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/remixicon@4.5.0/fonts/remixicon.css"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased">
        <TranslationsProvider
          namespaces={i18bNamespaces}
          locale={locale}
          resources={resources}
        >
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </TranslationsProvider>
      </body>
    </html>
  );
}
